# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Marco Afonso
author: Marco Afonso
email: hi@marcoafonso.pt
phone: +351 962 423 141
description: >- # this means to ignore newlines until "baseurl:"
  A programmer passionate about graphic design, 
  stubborn to the pixel. Has done freelance work 
  in branding and promotional material. Currently 
  ending a bachelor degree in Digital Games and 
  Multimedia and interning at Sound Particles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcoafonso.pt" # the base hostname & protocol for your site, e.g. http://example.com

#SASS COMFIG
sass:
    style: compressed

#SOCIAL MEDIA
facebook: https://www.facebook.com/marcoafonso.work/
linkedin: https://www.linkedin.com/in/marcoafonsoinfo/
behance:  https://www.behance.net/marcoafonso

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-minifier

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - deploy.sh
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
